### PR TITLE
Pythonification

### PR DESCRIPTION
**Pull request by PatrickMassot**
I wanted to try modifying some part of the code, but first I went through a round of cleanup and warning removal. This is meant to make no difference at all when running this code, except for suppressing python warnings. It also makes a difference when running mypy which checks a lot more.

### CODE REVIEW

**Comment by mpedramfar** [comment]
Thanks!

**Comment by mpedramfar** [comment]
There seems to be an issue with ClassVar. I use jsonpickle to turn python objects into json to be used later in the javascript code. When jsonpickle sees a variable specified as ClassVar, it simply ignores it. I fixed this, and a few other issues, in the latest commit.

**Comment by PatrickMassot** [comment]
I'm sorry I didn't see that. The weird thing is the NNG still seemed to work fine after my commit. Also I think your fix fixes the wrong thing. You should have fixed the broken jsonification instead of breaking the class declaration. This `type` is a textbook example of a class variable, you would never ever want to assign it while creating an instance. And this change forces you to use named arguments for many instance creations taking exactly one argument, which looks weird.

**Comment by mpedramfar** [comment]
You're right. `type` is a class variable. That was a quick fix so that I could focus on some other issues. I've fixed the behaviour of `jsonpickle` now.
As for why it might've seemed to work, one possibility is the browser cache. The browser saved an old version of `game_data.js` and these changes were purely in the backend, nothing in the frontend. So it seemed like the new `game_data.js` works fine, while an old version was being used. Another possibility is related to the way progress was saved in the game. I've made some changes so that issue can't happen anymore.

**Pull request merged**
